# Generated by Django 6.0.4 on 2026-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='other_role_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='other_role_title_normalized',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
