# Generated by Django 6.0.4 on 2026-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_first_name_submission_last_name_and_more'),
        ('surveys', '0002_formfield_translations_qrcampaign_default_language_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'mobile_number_normalized'], name='submissions_campaig_181a75_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'mobile_number_normalized', 'role'], name='submissions_campaig_eca746_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'mobile_number_normalized', 'other_role_title_normalized'], name='submissions_campaig_f902ba_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['candidate', 'campaign', 'submitted_at'], name='submissions_candida_febc22_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'status', 'submitted_at'], name='submissions_campaig_32dccb_idx'),
        ),
    ]
