# Generated by Django 6.0.4 on 2026-05-02 07:00

import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='qrcampaign',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='qrcampaign',
            name='enabled_languages',
            field=models.JSONField(default=surveys.models.default_enabled_languages),
        ),
    ]
